language: node_js
node_js:
  - "8"
  - "9"
  - "10"

cache:
  directories:
    - "node_modules"

branches:
  only:
  - master

install:
  - yarn install
  - yarn run build

script:
  - echo "Skipping tests"

jobs: 
  include:
    - stage: Deploy
      node_js: "10"
      install:
        - yarn install
        - yarn run build
      script:
        - echo "Skipping tests"
      deploy:
        provider: pages
        keep-history: true
        skip-cleanup: true
        github-token: $GITHUB_ACCESS_TOKEN
        target-branch: gh-pages
        local-dir: docs/.vuepress/dist
        on:
          branch: master

notifications:
  email: false