language: node_js
node_js:
  - "8"
  - "9"
  - "10"

cache:
  directories:
    - "node_modules"

branches:
  only:
  - master

install:
  - yarn install
  - yarn run build

script:
  - echo "Skipping tests"

deploy:
  provider: pages
  skip-cleanup: true
  committer-from-gh: true
  github-token: $GITHUB_ACCESS_TOKEN
  target-branch: gh-pages
  local-dir: docs/.vuepress/dist
  on:
    branch: master

notifications:
  email: false